apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-bazar
  labels:
    app: book-bazar
spec:
  replicas: 8
  selector:
    matchLabels:
      app: book-bazar
  template:
    metadata:
      labels:
        app: book-bazar
    spec:
      containers:
      - name: book-bazar
        image: hiranmoy36/book-bazar
        imagePullPolicy: Always
        command: ["/root/binary","start"]
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
