apiVersion: v1
kind: Service
metadata:
  name: ngnix-service
spec:
  selector:
    app: book-bazar
  type: NodePort
  ports:
  - protocol: TCP
    port: 30000
    targetPort: 8080
    nodePort: 30000
